/**
 * SUTRA-4.1 — candidate test scaffold generation from graph issues.
 * Stubs only — may not compile, not run in CI.
 */

import fs from "node:fs";
import path from "node:path";
import type { SutraGraph, SutraIssue, IssueKind } from "./types.js";

export const SCAFFOLD_BANNER =
  "// CANDIDATE — generated by Sutra, not run automatically";

export const SCAFFOLD_KINDS: IssueKind[] = [
  "orphaned_endpoint",
  "contract_missing_route",
];

/** Safe filename from issue node (METHOD /path). */
export function scaffoldFileName(issue: SutraIssue): string {
  const slug = issue.node
    .replace(/\s+/g, "-")
    .replace(/[^a-zA-Z0-9/_-]/g, "")
    .replace(/\//g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `${issue.kind}-${slug || "unknown"}.test.ts`;
}

/** Generate candidate test stub content for one issue. */
export function generateStub(issue: SutraIssue): string {
  const [method, ...pathParts] = issue.node.split(" ");
  const routePath = pathParts.join(" ") || issue.node;

  return `${SCAFFOLD_BANNER}
// Issue: ${issue.kind} — ${issue.message}
// Feature: ${issue.feature}

import { describe, it, expect } from "vitest";

describe("candidate: ${issue.kind} — ${routePath}", () => {
  it.todo("verify route exists for ${method ?? "GET"} ${routePath}");
  // Candidate stub — implement route handler or fix client call.
  // Sutra flagged: ${issue.message}
});
`;
}

export interface ScaffoldOptions {
  outDir: string;
  kinds: IssueKind[];
  force?: boolean;
}

export interface ScaffoldResult {
  written: string[];
  skipped: string[];
}

/** Write candidate test stubs for matching issues. Never overwrites without force. */
export function writeScaffolds(
  graph: SutraGraph,
  opts: ScaffoldOptions,
): ScaffoldResult {
  const written: string[] = [];
  const skipped: string[] = [];

  fs.mkdirSync(opts.outDir, { recursive: true });

  const issues = graph.issues.filter((i) => opts.kinds.includes(i.kind));

  for (const issue of issues) {
    const fileName = scaffoldFileName(issue);
    const filePath = path.join(opts.outDir, fileName);

    if (fs.existsSync(filePath) && !opts.force) {
      skipped.push(filePath);
      continue;
    }

    fs.writeFileSync(filePath, generateStub(issue), "utf8");
    written.push(filePath);
  }

  return { written, skipped };
}
